[project]
name = "book-recorder"
version = "0.1.0"
description = ""
authors = [
  { name = "Ryota Jin" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "streamlit>=1.41.1,<2.0.0",
  "watchdog>=6.0.0",
  "xmltodict>=0.14.2,<0.15.0",
]
